CREATE TABLE [dbo].[Products]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Type INT NOT NULL,
	Name NVARCHAR(1000) NOT NULL,
	Material INT NOT NULL,
	Description NVARCHAR(4000) NOT NULL,
	Articul NVARCHAR(256) NOT NULL,
	Timestamp DATETIME NOT NULL DEFAULT(GETUTCDATE())
)
